services:
  ytdlp-sync:
    build: .
    container_name: ytdlp-sync-test
    volumes:
      - ./playlists/:/playlists
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - PLAYLIST_ID=${PLAYLIST_ID}
